baseURL: https://m2mgateway.github.com/at-manual/
languageCode: en-US
title: AT Command Reference Manual
theme: hugo-book

disablePathToLower: true
enableGitInfo: true
disableKinds: [taxonomy, taxonomyTerm]

params:
  BookRepo: https://github.com/M2MGateway/at-manual
  BookEditPath: edit/main

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lexers:
      - assets/at-command-lexer.xml
