baseURL: https://m2mgateway.github.com/at-manual/
languageCode: en-US
title: AT Command Reference Manual
theme: hugo-book

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lexers:
      - assets/at-command-lexer.xml
